# GLOBAL SITE SETTINGS

cname: www.themitchinghour.com

# META
title: The Mitching Hour
title_homepage: The Mitching Hour - A Ghoulish Twitch Show
company:
description: The Mitching Hour is a horror themed Twitch channel that covers movies, games, comics and popular culture.

# SITE DEFAULTS
site_tagline: "<span class='font-weight-normal'>Coming</span> Soon-ish"
site_tagline_final: "THURSDAYS <span class='font-normal'>at</span> MIDNIGHT"

# DEVELOPER
allow_robots: false
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/mitchinghour.com
github_repo_name: mitchinghour.com
jekyll_version: 3.5.0

# OFFICES
offices:
  - title:
    address:
    phone:
    email:

# SOCIAL MEDIA
facebook: "#lol"
twitter: "https://www.twitter.com/saveterry"
instagram: https://www.instagram.com/themitchinghour/
youtube: https://www.youtube.com/channel/UCyhc20wvZZ_ODC-EzSErDjg
youtube_subscribe: https://www.youtube.com/channel/UCyhc20wvZZ_ODC-EzSErDjg

# GOOGLE
google_analytics: "UA-XXXXXXXX-X"

# AUTHOR
author:
  title: Mitch
  url: http://liquidvisual.com
  logo: /assets/img/ui/logo-mark.svg
  description: Site by liquidvisual